// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/views/weight/weight_history_view_redundancy_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:blood_pressure_monitor/models/health_data.dart' as _i3;
import 'package:blood_pressure_monitor/viewmodels/weight_viewmodel.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [WeightViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeightViewModel extends _i1.Mock implements _i2.WeightViewModel {
  MockWeightViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.WeightEntry> get entries => (super.noSuchMethod(
        Invocation.getter(#entries),
        returnValue: <_i3.WeightEntry>[],
      ) as List<_i3.WeightEntry>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get isSubmitting => (super.noSuchMethod(
        Invocation.getter(#isSubmitting),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> loadEntries({
    DateTime? from,
    DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadEntries,
          [],
          {
            #from: from,
            #to: to,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> saveWeightEntry({
    int? id,
    required double? weightValue,
    required _i3.WeightUnit? unit,
    required DateTime? recordedAt,
    String? notes,
    String? saltIntake,
    String? exerciseLevel,
    String? stressLevel,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWeightEntry,
          [],
          {
            #id: id,
            #weightValue: weightValue,
            #unit: unit,
            #recordedAt: recordedAt,
            #notes: notes,
            #saltIntake: saltIntake,
            #exerciseLevel: exerciseLevel,
            #stressLevel: stressLevel,
          },
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<String?> deleteWeightEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWeightEntry,
          [id],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  void clearError() => super.noSuchMethod(
        Invocation.method(
          #clearError,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
