// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/services/analytics_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blood_pressure_monitor/models/health_data.dart' as _i2;
import 'package:blood_pressure_monitor/models/reading.dart' as _i5;
import 'package:blood_pressure_monitor/services/reading_service.dart' as _i3;
import 'package:blood_pressure_monitor/services/sleep_service.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSleepEntry_0 extends _i1.SmartFake implements _i2.SleepEntry {
  _FakeSleepEntry_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReadingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingService extends _i1.Mock implements _i3.ReadingService {
  MockReadingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<int> createReading(_i5.Reading? reading) => (super.noSuchMethod(
        Invocation.method(
          #createReading,
          [reading],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i5.Reading?> getReading(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getReading,
          [id],
        ),
        returnValue: _i4.Future<_i5.Reading?>.value(),
      ) as _i4.Future<_i5.Reading?>);

  @override
  _i4.Future<List<_i5.Reading>> getReadingsByProfile(
    int? profileId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsByProfile,
          [profileId],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i5.Reading>>.value(<_i5.Reading>[]),
      ) as _i4.Future<List<_i5.Reading>>);

  @override
  _i4.Future<List<_i5.Reading>> getReadingsInTimeRange(
    int? profileId,
    DateTime? startTime,
    DateTime? endTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsInTimeRange,
          [
            profileId,
            startTime,
            endTime,
          ],
        ),
        returnValue: _i4.Future<List<_i5.Reading>>.value(<_i5.Reading>[]),
      ) as _i4.Future<List<_i5.Reading>>);

  @override
  _i4.Future<_i5.Reading?> getLatestReading(int? profileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestReading,
          [profileId],
        ),
        returnValue: _i4.Future<_i5.Reading?>.value(),
      ) as _i4.Future<_i5.Reading?>);

  @override
  _i4.Future<int> updateReading(_i5.Reading? reading) => (super.noSuchMethod(
        Invocation.method(
          #updateReading,
          [reading],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> deleteReading(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReading,
          [id],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getReadingCount(int? profileId) => (super.noSuchMethod(
        Invocation.method(
          #getReadingCount,
          [profileId],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<List<_i5.Reading>> getReadingsByTag(
    int? profileId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsByTag,
          [
            profileId,
            tag,
          ],
        ),
        returnValue: _i4.Future<List<_i5.Reading>>.value(<_i5.Reading>[]),
      ) as _i4.Future<List<_i5.Reading>>);

  @override
  _i4.Future<List<_i5.ReadingGroup>> getGroupsInRange({
    required int? profileId,
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupsInRange,
          [],
          {
            #profileId: profileId,
            #start: start,
            #end: end,
          },
        ),
        returnValue:
            _i4.Future<List<_i5.ReadingGroup>>.value(<_i5.ReadingGroup>[]),
      ) as _i4.Future<List<_i5.ReadingGroup>>);

  @override
  _i4.Future<List<_i5.Reading>> getReadingsByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsByIds,
          [ids],
        ),
        returnValue: _i4.Future<List<_i5.Reading>>.value(<_i5.Reading>[]),
      ) as _i4.Future<List<_i5.Reading>>);
}

/// A class which mocks [SleepService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSleepService extends _i1.Mock implements _i6.SleepService {
  MockSleepService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SleepEntry> createSleepEntry(_i2.SleepEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSleepEntry,
          [entry],
        ),
        returnValue: _i4.Future<_i2.SleepEntry>.value(_FakeSleepEntry_0(
          this,
          Invocation.method(
            #createSleepEntry,
            [entry],
          ),
        )),
      ) as _i4.Future<_i2.SleepEntry>);

  @override
  _i4.Future<_i2.SleepEntry?> getSleepEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getSleepEntry,
          [id],
        ),
        returnValue: _i4.Future<_i2.SleepEntry?>.value(),
      ) as _i4.Future<_i2.SleepEntry?>);

  @override
  _i4.Future<List<_i2.SleepEntry>> listSleepEntries({
    required int? profileId,
    DateTime? from,
    DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listSleepEntries,
          [],
          {
            #profileId: profileId,
            #from: from,
            #to: to,
          },
        ),
        returnValue: _i4.Future<List<_i2.SleepEntry>>.value(<_i2.SleepEntry>[]),
      ) as _i4.Future<List<_i2.SleepEntry>>);

  @override
  _i4.Future<_i2.SleepEntry> updateSleepEntry(_i2.SleepEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSleepEntry,
          [entry],
        ),
        returnValue: _i4.Future<_i2.SleepEntry>.value(_FakeSleepEntry_0(
          this,
          Invocation.method(
            #updateSleepEntry,
            [entry],
          ),
        )),
      ) as _i4.Future<_i2.SleepEntry>);

  @override
  _i4.Future<bool> deleteSleepEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSleepEntry,
          [id],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i2.SleepEntry?> findSleepForMorningReading({
    required int? profileId,
    required DateTime? readingTime,
    int? lookbackHours = 18,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findSleepForMorningReading,
          [],
          {
            #profileId: profileId,
            #readingTime: readingTime,
            #lookbackHours: lookbackHours,
          },
        ),
        returnValue: _i4.Future<_i2.SleepEntry?>.value(),
      ) as _i4.Future<_i2.SleepEntry?>);

  @override
  _i4.Future<bool> isDuplicate({
    required int? profileId,
    required DateTime? startedAt,
    required _i2.SleepSource? source,
    String? sourceMetadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicate,
          [],
          {
            #profileId: profileId,
            #startedAt: startedAt,
            #source: source,
            #sourceMetadata: sourceMetadata,
          },
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
