// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/services/stats_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:blood_pressure_monitor/models/health_data.dart' as _i2;
import 'package:blood_pressure_monitor/models/medication.dart' as _i3;
import 'package:blood_pressure_monitor/models/reading.dart' as _i6;
import 'package:blood_pressure_monitor/services/medication_intake_service.dart'
    as _i9;
import 'package:blood_pressure_monitor/services/reading_service.dart' as _i4;
import 'package:blood_pressure_monitor/services/sleep_service.dart' as _i8;
import 'package:blood_pressure_monitor/services/weight_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeightEntry_0 extends _i1.SmartFake implements _i2.WeightEntry {
  _FakeWeightEntry_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSleepEntry_1 extends _i1.SmartFake implements _i2.SleepEntry {
  _FakeSleepEntry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMedicationIntake_2 extends _i1.SmartFake
    implements _i3.MedicationIntake {
  _FakeMedicationIntake_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ReadingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingService extends _i1.Mock implements _i4.ReadingService {
  MockReadingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<int> createReading(_i6.Reading? reading) => (super.noSuchMethod(
        Invocation.method(
          #createReading,
          [reading],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i6.Reading?> getReading(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getReading,
          [id],
        ),
        returnValue: _i5.Future<_i6.Reading?>.value(),
      ) as _i5.Future<_i6.Reading?>);

  @override
  _i5.Future<List<_i6.Reading>> getReadingsByProfile(
    int? profileId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsByProfile,
          [profileId],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i6.Reading>>.value(<_i6.Reading>[]),
      ) as _i5.Future<List<_i6.Reading>>);

  @override
  _i5.Future<List<_i6.Reading>> getReadingsInTimeRange(
    int? profileId,
    DateTime? startTime,
    DateTime? endTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsInTimeRange,
          [
            profileId,
            startTime,
            endTime,
          ],
        ),
        returnValue: _i5.Future<List<_i6.Reading>>.value(<_i6.Reading>[]),
      ) as _i5.Future<List<_i6.Reading>>);

  @override
  _i5.Future<_i6.Reading?> getLatestReading(int? profileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestReading,
          [profileId],
        ),
        returnValue: _i5.Future<_i6.Reading?>.value(),
      ) as _i5.Future<_i6.Reading?>);

  @override
  _i5.Future<int> updateReading(_i6.Reading? reading) => (super.noSuchMethod(
        Invocation.method(
          #updateReading,
          [reading],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteReading(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReading,
          [id],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> deleteAllByProfile(int? profileId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllByProfile,
          [profileId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> getReadingCount(int? profileId) => (super.noSuchMethod(
        Invocation.method(
          #getReadingCount,
          [profileId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<List<_i6.Reading>> getReadingsByTag(
    int? profileId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsByTag,
          [
            profileId,
            tag,
          ],
        ),
        returnValue: _i5.Future<List<_i6.Reading>>.value(<_i6.Reading>[]),
      ) as _i5.Future<List<_i6.Reading>>);

  @override
  _i5.Future<List<_i6.ReadingGroup>> getGroupsInRange({
    required int? profileId,
    required DateTime? start,
    required DateTime? end,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupsInRange,
          [],
          {
            #profileId: profileId,
            #start: start,
            #end: end,
          },
        ),
        returnValue:
            _i5.Future<List<_i6.ReadingGroup>>.value(<_i6.ReadingGroup>[]),
      ) as _i5.Future<List<_i6.ReadingGroup>>);

  @override
  _i5.Future<List<_i6.Reading>> getReadingsByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i6.Reading>>.value(<_i6.Reading>[]),
      ) as _i5.Future<List<_i6.Reading>>);
}

/// A class which mocks [WeightService].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeightService extends _i1.Mock implements _i7.WeightService {
  MockWeightService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WeightEntry> createWeightEntry(_i2.WeightEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createWeightEntry,
          [entry],
        ),
        returnValue: _i5.Future<_i2.WeightEntry>.value(_FakeWeightEntry_0(
          this,
          Invocation.method(
            #createWeightEntry,
            [entry],
          ),
        )),
      ) as _i5.Future<_i2.WeightEntry>);

  @override
  _i5.Future<_i2.WeightEntry?> getWeightEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getWeightEntry,
          [id],
        ),
        returnValue: _i5.Future<_i2.WeightEntry?>.value(),
      ) as _i5.Future<_i2.WeightEntry?>);

  @override
  _i5.Future<List<_i2.WeightEntry>> listWeightEntries({
    required int? profileId,
    DateTime? from,
    DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listWeightEntries,
          [],
          {
            #profileId: profileId,
            #from: from,
            #to: to,
          },
        ),
        returnValue:
            _i5.Future<List<_i2.WeightEntry>>.value(<_i2.WeightEntry>[]),
      ) as _i5.Future<List<_i2.WeightEntry>>);

  @override
  _i5.Future<_i2.WeightEntry?> getLatestWeightEntry(int? profileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestWeightEntry,
          [profileId],
        ),
        returnValue: _i5.Future<_i2.WeightEntry?>.value(),
      ) as _i5.Future<_i2.WeightEntry?>);

  @override
  _i5.Future<_i2.WeightEntry> updateWeightEntry(_i2.WeightEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateWeightEntry,
          [entry],
        ),
        returnValue: _i5.Future<_i2.WeightEntry>.value(_FakeWeightEntry_0(
          this,
          Invocation.method(
            #updateWeightEntry,
            [entry],
          ),
        )),
      ) as _i5.Future<_i2.WeightEntry>);

  @override
  _i5.Future<int> deleteAllByProfile(int? profileId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllByProfile,
          [profileId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<bool> deleteWeightEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteWeightEntry,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<_i2.WeightEntry?> findWeightForReading({
    required int? profileId,
    required DateTime? readingTime,
    Duration? window = const Duration(hours: 1),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findWeightForReading,
          [],
          {
            #profileId: profileId,
            #readingTime: readingTime,
            #window: window,
          },
        ),
        returnValue: _i5.Future<_i2.WeightEntry?>.value(),
      ) as _i5.Future<_i2.WeightEntry?>);
}

/// A class which mocks [SleepService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSleepService extends _i1.Mock implements _i8.SleepService {
  MockSleepService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SleepEntry> createSleepEntry(_i2.SleepEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #createSleepEntry,
          [entry],
        ),
        returnValue: _i5.Future<_i2.SleepEntry>.value(_FakeSleepEntry_1(
          this,
          Invocation.method(
            #createSleepEntry,
            [entry],
          ),
        )),
      ) as _i5.Future<_i2.SleepEntry>);

  @override
  _i5.Future<_i2.SleepEntry?> getSleepEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getSleepEntry,
          [id],
        ),
        returnValue: _i5.Future<_i2.SleepEntry?>.value(),
      ) as _i5.Future<_i2.SleepEntry?>);

  @override
  _i5.Future<List<_i2.SleepEntry>> listSleepEntries({
    required int? profileId,
    DateTime? from,
    DateTime? to,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listSleepEntries,
          [],
          {
            #profileId: profileId,
            #from: from,
            #to: to,
          },
        ),
        returnValue: _i5.Future<List<_i2.SleepEntry>>.value(<_i2.SleepEntry>[]),
      ) as _i5.Future<List<_i2.SleepEntry>>);

  @override
  _i5.Future<_i2.SleepEntry> updateSleepEntry(_i2.SleepEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSleepEntry,
          [entry],
        ),
        returnValue: _i5.Future<_i2.SleepEntry>.value(_FakeSleepEntry_1(
          this,
          Invocation.method(
            #updateSleepEntry,
            [entry],
          ),
        )),
      ) as _i5.Future<_i2.SleepEntry>);

  @override
  _i5.Future<bool> deleteSleepEntry(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteSleepEntry,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteAllByProfile(int? profileId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllByProfile,
          [profileId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i2.SleepEntry?> findSleepForMorningReading({
    required int? profileId,
    required DateTime? readingTime,
    int? lookbackHours = 18,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findSleepForMorningReading,
          [],
          {
            #profileId: profileId,
            #readingTime: readingTime,
            #lookbackHours: lookbackHours,
          },
        ),
        returnValue: _i5.Future<_i2.SleepEntry?>.value(),
      ) as _i5.Future<_i2.SleepEntry?>);

  @override
  _i5.Future<bool> isDuplicate({
    required int? profileId,
    required DateTime? startedAt,
    required _i2.SleepSource? source,
    String? sourceMetadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #isDuplicate,
          [],
          {
            #profileId: profileId,
            #startedAt: startedAt,
            #source: source,
            #sourceMetadata: sourceMetadata,
          },
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [MedicationIntakeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationIntakeService extends _i1.Mock
    implements _i9.MedicationIntakeService {
  MockMedicationIntakeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.MedicationIntake> logIntake(_i3.MedicationIntake? intake) =>
      (super.noSuchMethod(
        Invocation.method(
          #logIntake,
          [intake],
        ),
        returnValue:
            _i5.Future<_i3.MedicationIntake>.value(_FakeMedicationIntake_2(
          this,
          Invocation.method(
            #logIntake,
            [intake],
          ),
        )),
      ) as _i5.Future<_i3.MedicationIntake>);

  @override
  _i5.Future<List<_i3.MedicationIntake>> logGroupIntake({
    int? groupId,
    required List<int>? medicationIds,
    required int? profileId,
    required DateTime? takenAt,
    DateTime? scheduledFor,
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logGroupIntake,
          [],
          {
            #groupId: groupId,
            #medicationIds: medicationIds,
            #profileId: profileId,
            #takenAt: takenAt,
            #scheduledFor: scheduledFor,
            #note: note,
          },
        ),
        returnValue: _i5.Future<List<_i3.MedicationIntake>>.value(
            <_i3.MedicationIntake>[]),
      ) as _i5.Future<List<_i3.MedicationIntake>>);

  @override
  _i5.Future<_i3.MedicationIntake?> getIntake(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getIntake,
          [id],
        ),
        returnValue: _i5.Future<_i3.MedicationIntake?>.value(),
      ) as _i5.Future<_i3.MedicationIntake?>);

  @override
  _i5.Future<List<_i3.MedicationIntake>> listIntakes({
    required int? profileId,
    DateTime? from,
    DateTime? to,
    int? medicationId,
    int? groupId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #listIntakes,
          [],
          {
            #profileId: profileId,
            #from: from,
            #to: to,
            #medicationId: medicationId,
            #groupId: groupId,
          },
        ),
        returnValue: _i5.Future<List<_i3.MedicationIntake>>.value(
            <_i3.MedicationIntake>[]),
      ) as _i5.Future<List<_i3.MedicationIntake>>);

  @override
  _i5.Future<List<_i3.MedicationIntake>> findIntakesAround({
    required int? profileId,
    required DateTime? anchor,
    Duration? window = const Duration(minutes: 30),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #findIntakesAround,
          [],
          {
            #profileId: profileId,
            #anchor: anchor,
            #window: window,
          },
        ),
        returnValue: _i5.Future<List<_i3.MedicationIntake>>.value(
            <_i3.MedicationIntake>[]),
      ) as _i5.Future<List<_i3.MedicationIntake>>);

  @override
  _i5.Future<List<_i3.MedicationIntake>> intakesByIds(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(
          #intakesByIds,
          [ids],
        ),
        returnValue: _i5.Future<List<_i3.MedicationIntake>>.value(
            <_i3.MedicationIntake>[]),
      ) as _i5.Future<List<_i3.MedicationIntake>>);

  @override
  _i3.IntakeStatus calculateStatus({
    required _i3.MedicationIntake? intake,
    String? scheduleMetadata,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateStatus,
          [],
          {
            #intake: intake,
            #scheduleMetadata: scheduleMetadata,
          },
        ),
        returnValue: _i3.IntakeStatus.onTime,
      ) as _i3.IntakeStatus);

  @override
  _i5.Future<bool> deleteIntake(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteIntake,
          [id],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int> deleteAllByProfile(int? profileId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllByProfile,
          [profileId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);
}
