// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/views/analytics/widgets/time_range_selector_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:blood_pressure_monitor/utils/time_range.dart' as _i3;
import 'package:blood_pressure_monitor/viewmodels/analytics_viewmodel.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AnalyticsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsViewModel extends _i1.Mock
    implements _i2.AnalyticsViewModel {
  MockAnalyticsViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.TimeRange get selectedRange => (super.noSuchMethod(
        Invocation.getter(#selectedRange),
        returnValue: _i3.TimeRange.sevenDays,
      ) as _i3.TimeRange);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasData => (super.noSuchMethod(
        Invocation.getter(#hasData),
        returnValue: false,
      ) as bool);

  @override
  bool get showSleepOverlay => (super.noSuchMethod(
        Invocation.getter(#showSleepOverlay),
        returnValue: false,
      ) as bool);

  @override
  bool get smoothBpChart => (super.noSuchMethod(
        Invocation.getter(#smoothBpChart),
        returnValue: false,
      ) as bool);

  @override
  bool get smoothPulseChart => (super.noSuchMethod(
        Invocation.getter(#smoothPulseChart),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setTimeRange(_i3.TimeRange? range) => super.noSuchMethod(
        Invocation.method(
          #setTimeRange,
          [range],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void invalidateCache() => super.noSuchMethod(
        Invocation.method(
          #invalidateCache,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> toggleBpSmoothing() => (super.noSuchMethod(
        Invocation.method(
          #toggleBpSmoothing,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void togglePulseSmoothing() => super.noSuchMethod(
        Invocation.method(
          #togglePulseSmoothing,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> toggleSleepOverlay() => (super.noSuchMethod(
        Invocation.method(
          #toggleSleepOverlay,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> loadData({
    bool? forceRefresh = false,
    bool? forceOverlayRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadData,
          [],
          {
            #forceRefresh: forceRefresh,
            #forceOverlayRefresh: forceOverlayRefresh,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
