// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/views/history/history_home_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:blood_pressure_monitor/viewmodels/history_home_viewmodel.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [HistoryHomeViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryHomeViewModel extends _i1.Mock
    implements _i2.HistoryHomeViewModel {
  MockHistoryHomeViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoadingBP => (super.noSuchMethod(
        Invocation.getter(#isLoadingBP),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingWeight => (super.noSuchMethod(
        Invocation.getter(#isLoadingWeight),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingSleep => (super.noSuchMethod(
        Invocation.getter(#isLoadingSleep),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingMedication => (super.noSuchMethod(
        Invocation.getter(#isLoadingMedication),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<void> loadAllStats() => (super.noSuchMethod(
        Invocation.method(
          #loadAllStats,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadBPStats() => (super.noSuchMethod(
        Invocation.method(
          #loadBPStats,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadWeightStats() => (super.noSuchMethod(
        Invocation.method(
          #loadWeightStats,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadSleepStats() => (super.noSuchMethod(
        Invocation.method(
          #loadSleepStats,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> loadMedicationStats() => (super.noSuchMethod(
        Invocation.method(
          #loadMedicationStats,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
