// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/views/appearance_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:blood_pressure_monitor/models/theme_settings.dart' as _i2;
import 'package:blood_pressure_monitor/models/units_preference.dart' as _i4;
import 'package:blood_pressure_monitor/services/units_preference_service.dart'
    as _i8;
import 'package:blood_pressure_monitor/viewmodels/theme_viewmodel.dart' as _i5;
import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeThemeSettings_0 extends _i1.SmartFake implements _i2.ThemeSettings {
  _FakeThemeSettings_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_1 extends _i1.SmartFake implements _i3.ThemeData {
  _FakeThemeData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

class _FakeUnitsPreference_2 extends _i1.SmartFake
    implements _i4.UnitsPreference {
  _FakeUnitsPreference_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ThemeViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeViewModel extends _i1.Mock implements _i5.ThemeViewModel {
  MockThemeViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ThemeSettings get settings => (super.noSuchMethod(
        Invocation.getter(#settings),
        returnValue: _FakeThemeSettings_0(
          this,
          Invocation.getter(#settings),
        ),
      ) as _i2.ThemeSettings);

  @override
  _i2.AppThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i2.AppThemeMode.light,
      ) as _i2.AppThemeMode);

  @override
  _i2.AccentColor get accentColor => (super.noSuchMethod(
        Invocation.getter(#accentColor),
        returnValue: _i2.AccentColor.teal,
      ) as _i2.AccentColor);

  @override
  _i2.FontScaleOption get fontScale => (super.noSuchMethod(
        Invocation.getter(#fontScale),
        returnValue: _i2.FontScaleOption.normal,
      ) as _i2.FontScaleOption);

  @override
  bool get highContrastMode => (super.noSuchMethod(
        Invocation.getter(#highContrastMode),
        returnValue: false,
      ) as bool);

  @override
  _i3.ThemeMode get materialThemeMode => (super.noSuchMethod(
        Invocation.getter(#materialThemeMode),
        returnValue: _i3.ThemeMode.system,
      ) as _i3.ThemeMode);

  @override
  _i3.ThemeData get lightTheme => (super.noSuchMethod(
        Invocation.getter(#lightTheme),
        returnValue: _FakeThemeData_1(
          this,
          Invocation.getter(#lightTheme),
        ),
      ) as _i3.ThemeData);

  @override
  _i3.ThemeData get darkTheme => (super.noSuchMethod(
        Invocation.getter(#darkTheme),
        returnValue: _FakeThemeData_1(
          this,
          Invocation.getter(#darkTheme),
        ),
      ) as _i3.ThemeData);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> setThemeMode(_i2.AppThemeMode? mode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setAccentColor(_i2.AccentColor? color) =>
      (super.noSuchMethod(
        Invocation.method(
          #setAccentColor,
          [color],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setFontScale(_i2.FontScaleOption? scale) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFontScale,
          [scale],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> toggleHighContrastMode() => (super.noSuchMethod(
        Invocation.method(
          #toggleHighContrastMode,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [UnitsPreferenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUnitsPreferenceService extends _i1.Mock
    implements _i8.UnitsPreferenceService {
  MockUnitsPreferenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.UnitsPreference> getUnitsPreference() => (super.noSuchMethod(
        Invocation.method(
          #getUnitsPreference,
          [],
        ),
        returnValue:
            _i6.Future<_i4.UnitsPreference>.value(_FakeUnitsPreference_2(
          this,
          Invocation.method(
            #getUnitsPreference,
            [],
          ),
        )),
      ) as _i6.Future<_i4.UnitsPreference>);

  @override
  _i6.Future<void> saveUnitsPreference(_i4.UnitsPreference? preference) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveUnitsPreference,
          [preference],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearUnitsPreference() => (super.noSuchMethod(
        Invocation.method(
          #clearUnitsPreference,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
