// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/views/home_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:blood_pressure_monitor/models/lock_state.dart' as _i3;
import 'package:blood_pressure_monitor/models/reading.dart' as _i5;
import 'package:blood_pressure_monitor/utils/validators.dart' as _i2;
import 'package:blood_pressure_monitor/viewmodels/blood_pressure_viewmodel.dart'
    as _i4;
import 'package:blood_pressure_monitor/viewmodels/history_home_viewmodel.dart'
    as _i11;
import 'package:blood_pressure_monitor/viewmodels/lock_viewmodel.dart' as _i8;
import 'package:flutter/services.dart' as _i9;
import 'package:flutter/widgets.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValidationResult_0 extends _i1.SmartFake
    implements _i2.ValidationResult {
  _FakeValidationResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppLockState_1 extends _i1.SmartFake implements _i3.AppLockState {
  _FakeAppLockState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BloodPressureViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockBloodPressureViewModel extends _i1.Mock
    implements _i4.BloodPressureViewModel {
  MockBloodPressureViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.Reading> get readings => (super.noSuchMethod(
        Invocation.getter(#readings),
        returnValue: <_i5.Reading>[],
      ) as List<_i5.Reading>);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> loadReadings({bool? clearError = true}) =>
      (super.noSuchMethod(
        Invocation.method(
          #loadReadings,
          [],
          {#clearError: clearError},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i2.ValidationResult> addReading(
    _i5.Reading? reading, {
    bool? confirmOverride = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addReading,
          [reading],
          {#confirmOverride: confirmOverride},
        ),
        returnValue:
            _i6.Future<_i2.ValidationResult>.value(_FakeValidationResult_0(
          this,
          Invocation.method(
            #addReading,
            [reading],
            {#confirmOverride: confirmOverride},
          ),
        )),
      ) as _i6.Future<_i2.ValidationResult>);

  @override
  _i6.Future<_i2.ValidationResult> updateReading(
    _i5.Reading? reading, {
    bool? confirmOverride = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReading,
          [reading],
          {#confirmOverride: confirmOverride},
        ),
        returnValue:
            _i6.Future<_i2.ValidationResult>.value(_FakeValidationResult_0(
          this,
          Invocation.method(
            #updateReading,
            [reading],
            {#confirmOverride: confirmOverride},
          ),
        )),
      ) as _i6.Future<_i2.ValidationResult>);

  @override
  _i6.Future<void> deleteReading(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReading,
          [id],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [LockViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockLockViewModel extends _i1.Mock implements _i8.LockViewModel {
  MockLockViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AppLockState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeAppLockState_1(
          this,
          Invocation.getter(#state),
        ),
      ) as _i3.AppLockState);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAppLifecycleState(_i7.AppLifecycleState? state) =>
      super.noSuchMethod(
        Invocation.method(
          #didChangeAppLifecycleState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> unlockWithPin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #unlockWithPin,
          [pin],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> unlockWithBiometric() => (super.noSuchMethod(
        Invocation.method(
          #unlockWithBiometric,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  void lock() => super.noSuchMethod(
        Invocation.method(
          #lock,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> setPin(String? pin) => (super.noSuchMethod(
        Invocation.method(
          #setPin,
          [pin],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> changePin(
    String? oldPin,
    String? newPin,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePin,
          [
            oldPin,
            newPin,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> setBiometricEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setBiometricEnabled,
          [enabled],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setIdleTimeout(int? minutes) => (super.noSuchMethod(
        Invocation.method(
          #setIdleTimeout,
          [minutes],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void recordActivity() => super.noSuchMethod(
        Invocation.method(
          #recordActivity,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> refreshBiometricAvailability() => (super.noSuchMethod(
        Invocation.method(
          #refreshBiometricAvailability,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> didPopRoute() => (super.noSuchMethod(
        Invocation.method(
          #didPopRoute,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  bool handleStartBackGesture(_i9.PredictiveBackEvent? backEvent) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleStartBackGesture,
          [backEvent],
        ),
        returnValue: false,
      ) as bool);

  @override
  void handleUpdateBackGestureProgress(_i9.PredictiveBackEvent? backEvent) =>
      super.noSuchMethod(
        Invocation.method(
          #handleUpdateBackGestureProgress,
          [backEvent],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCommitBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCommitBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void handleCancelBackGesture() => super.noSuchMethod(
        Invocation.method(
          #handleCancelBackGesture,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> didPushRoute(String? route) => (super.noSuchMethod(
        Invocation.method(
          #didPushRoute,
          [route],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> didPushRouteInformation(
          _i10.RouteInformation? routeInformation) =>
      (super.noSuchMethod(
        Invocation.method(
          #didPushRouteInformation,
          [routeInformation],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  void didChangeMetrics() => super.noSuchMethod(
        Invocation.method(
          #didChangeMetrics,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeTextScaleFactor() => super.noSuchMethod(
        Invocation.method(
          #didChangeTextScaleFactor,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangePlatformBrightness() => super.noSuchMethod(
        Invocation.method(
          #didChangePlatformBrightness,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeLocales(List<_i7.Locale>? locales) => super.noSuchMethod(
        Invocation.method(
          #didChangeLocales,
          [locales],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeViewFocus(_i7.ViewFocusEvent? event) => super.noSuchMethod(
        Invocation.method(
          #didChangeViewFocus,
          [event],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i7.AppExitResponse> didRequestAppExit() => (super.noSuchMethod(
        Invocation.method(
          #didRequestAppExit,
          [],
        ),
        returnValue:
            _i6.Future<_i7.AppExitResponse>.value(_i7.AppExitResponse.exit),
      ) as _i6.Future<_i7.AppExitResponse>);

  @override
  void didHaveMemoryPressure() => super.noSuchMethod(
        Invocation.method(
          #didHaveMemoryPressure,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void didChangeAccessibilityFeatures() => super.noSuchMethod(
        Invocation.method(
          #didChangeAccessibilityFeatures,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [HistoryHomeViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryHomeViewModel extends _i1.Mock
    implements _i11.HistoryHomeViewModel {
  MockHistoryHomeViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoadingBP => (super.noSuchMethod(
        Invocation.getter(#isLoadingBP),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingWeight => (super.noSuchMethod(
        Invocation.getter(#isLoadingWeight),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingSleep => (super.noSuchMethod(
        Invocation.getter(#isLoadingSleep),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoadingMedication => (super.noSuchMethod(
        Invocation.getter(#isLoadingMedication),
        returnValue: false,
      ) as bool);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> loadAllStats() => (super.noSuchMethod(
        Invocation.method(
          #loadAllStats,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadBPStats() => (super.noSuchMethod(
        Invocation.method(
          #loadBPStats,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadWeightStats() => (super.noSuchMethod(
        Invocation.method(
          #loadWeightStats,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadSleepStats() => (super.noSuchMethod(
        Invocation.method(
          #loadSleepStats,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> loadMedicationStats() => (super.noSuchMethod(
        Invocation.method(
          #loadMedicationStats,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> refresh() => (super.noSuchMethod(
        Invocation.method(
          #refresh,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
