// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/viewmodels/analytics_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:blood_pressure_monitor/models/analytics.dart' as _i2;
import 'package:blood_pressure_monitor/models/reading.dart' as _i7;
import 'package:blood_pressure_monitor/services/analytics_service.dart' as _i3;
import 'package:blood_pressure_monitor/utils/time_range.dart' as _i6;
import 'package:flutter/material.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHealthStats_0 extends _i1.SmartFake implements _i2.HealthStats {
  _FakeHealthStats_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeChartDataSet_1 extends _i1.SmartFake implements _i2.ChartDataSet {
  _FakeChartDataSet_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSleepCorrelationData_2 extends _i1.SmartFake
    implements _i2.SleepCorrelationData {
  _FakeSleepCorrelationData_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSleepStageSeries_3 extends _i1.SmartFake
    implements _i2.SleepStageSeries {
  _FakeSleepStageSeries_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTimeOfDayClassification_4 extends _i1.SmartFake
    implements _i3.TimeOfDayClassification {
  _FakeTimeOfDayClassification_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i3.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.HealthStats> calculateStats({
    required int? profileId,
    required DateTime? startDate,
    required DateTime? endDate,
    _i5.TimeOfDay? cutoff,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateStats,
          [],
          {
            #profileId: profileId,
            #startDate: startDate,
            #endDate: endDate,
            #cutoff: cutoff,
          },
        ),
        returnValue: _i4.Future<_i2.HealthStats>.value(_FakeHealthStats_0(
          this,
          Invocation.method(
            #calculateStats,
            [],
            {
              #profileId: profileId,
              #startDate: startDate,
              #endDate: endDate,
              #cutoff: cutoff,
            },
          ),
        )),
      ) as _i4.Future<_i2.HealthStats>);

  @override
  _i4.Future<_i2.ChartDataSet> getChartData({
    required int? profileId,
    required DateTime? startDate,
    required DateTime? endDate,
    required _i6.TimeRange? range,
    int? maxPoints = 90,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getChartData,
          [],
          {
            #profileId: profileId,
            #startDate: startDate,
            #endDate: endDate,
            #range: range,
            #maxPoints: maxPoints,
          },
        ),
        returnValue: _i4.Future<_i2.ChartDataSet>.value(_FakeChartDataSet_1(
          this,
          Invocation.method(
            #getChartData,
            [],
            {
              #profileId: profileId,
              #startDate: startDate,
              #endDate: endDate,
              #range: range,
              #maxPoints: maxPoints,
            },
          ),
        )),
      ) as _i4.Future<_i2.ChartDataSet>);

  @override
  _i4.Future<_i2.SleepCorrelationData> getSleepCorrelation({
    required int? profileId,
    required DateTime? startDate,
    required DateTime? endDate,
    _i5.TimeOfDay? cutoff,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSleepCorrelation,
          [],
          {
            #profileId: profileId,
            #startDate: startDate,
            #endDate: endDate,
            #cutoff: cutoff,
          },
        ),
        returnValue: _i4.Future<_i2.SleepCorrelationData>.value(
            _FakeSleepCorrelationData_2(
          this,
          Invocation.method(
            #getSleepCorrelation,
            [],
            {
              #profileId: profileId,
              #startDate: startDate,
              #endDate: endDate,
              #cutoff: cutoff,
            },
          ),
        )),
      ) as _i4.Future<_i2.SleepCorrelationData>);

  @override
  _i4.Future<_i2.SleepStageSeries> getSleepStageSeries({
    required int? profileId,
    required DateTime? startDate,
    required DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSleepStageSeries,
          [],
          {
            #profileId: profileId,
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i4.Future<_i2.SleepStageSeries>.value(_FakeSleepStageSeries_3(
          this,
          Invocation.method(
            #getSleepStageSeries,
            [],
            {
              #profileId: profileId,
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i4.Future<_i2.SleepStageSeries>);

  @override
  _i3.TimeOfDayClassification classifyByTimeOfDay(
    List<_i7.ReadingGroup>? groups,
    _i5.TimeOfDay? cutoff,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #classifyByTimeOfDay,
          [
            groups,
            cutoff,
          ],
        ),
        returnValue: _FakeTimeOfDayClassification_4(
          this,
          Invocation.method(
            #classifyByTimeOfDay,
            [
              groups,
              cutoff,
            ],
          ),
        ),
      ) as _i3.TimeOfDayClassification);
}
