// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/viewmodels/blood_pressure_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:blood_pressure_monitor/models/reading.dart' as _i4;
import 'package:blood_pressure_monitor/services/averaging_service.dart' as _i5;
import 'package:blood_pressure_monitor/services/reading_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReadingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadingService extends _i1.Mock implements _i2.ReadingService {
  MockReadingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> createReading(_i4.Reading? reading) => (super.noSuchMethod(
        Invocation.method(
          #createReading,
          [reading],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i4.Reading?> getReading(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getReading,
          [id],
        ),
        returnValue: _i3.Future<_i4.Reading?>.value(),
      ) as _i3.Future<_i4.Reading?>);

  @override
  _i3.Future<List<_i4.Reading>> getReadingsByProfile(
    int? profileId, {
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsByProfile,
          [profileId],
          {#limit: limit},
        ),
        returnValue: _i3.Future<List<_i4.Reading>>.value(<_i4.Reading>[]),
      ) as _i3.Future<List<_i4.Reading>>);

  @override
  _i3.Future<List<_i4.Reading>> getReadingsInTimeRange(
    int? profileId,
    DateTime? startTime,
    DateTime? endTime,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsInTimeRange,
          [
            profileId,
            startTime,
            endTime,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Reading>>.value(<_i4.Reading>[]),
      ) as _i3.Future<List<_i4.Reading>>);

  @override
  _i3.Future<_i4.Reading?> getLatestReading(int? profileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestReading,
          [profileId],
        ),
        returnValue: _i3.Future<_i4.Reading?>.value(),
      ) as _i3.Future<_i4.Reading?>);

  @override
  _i3.Future<int> updateReading(_i4.Reading? reading) => (super.noSuchMethod(
        Invocation.method(
          #updateReading,
          [reading],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteReading(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteReading,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getReadingCount(int? profileId) => (super.noSuchMethod(
        Invocation.method(
          #getReadingCount,
          [profileId],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i4.Reading>> getReadingsByTag(
    int? profileId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getReadingsByTag,
          [
            profileId,
            tag,
          ],
        ),
        returnValue: _i3.Future<List<_i4.Reading>>.value(<_i4.Reading>[]),
      ) as _i3.Future<List<_i4.Reading>>);
}

/// A class which mocks [AveragingService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAveragingService extends _i1.Mock implements _i5.AveragingService {
  MockAveragingService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createOrUpdateGroupsForReading(_i4.Reading? reading) =>
      (super.noSuchMethod(
        Invocation.method(
          #createOrUpdateGroupsForReading,
          [reading],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> recomputeGroupsForProfile(int? profileId) =>
      (super.noSuchMethod(
        Invocation.method(
          #recomputeGroupsForProfile,
          [profileId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteGroupsForReading(int? readingId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGroupsForReading,
          [readingId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
