// Mocks generated by Mockito 5.4.4 from annotations
// in blood_pressure_monitor/test/viewmodels/theme_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:blood_pressure_monitor/models/theme_settings.dart' as _i4;
import 'package:blood_pressure_monitor/services/theme_persistence_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ThemePersistenceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemePersistenceService extends _i1.Mock
    implements _i2.ThemePersistenceService {
  MockThemePersistenceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> saveThemeSettings(_i4.ThemeSettings? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveThemeSettings,
          [settings],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i4.ThemeSettings? loadThemeSettings() => (super.noSuchMethod(
        Invocation.method(
          #loadThemeSettings,
          [],
        ),
      ) as _i4.ThemeSettings?);

  @override
  _i3.Future<bool> clearThemeSettings() => (super.noSuchMethod(
        Invocation.method(
          #clearThemeSettings,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
