// Mocks generated by Mockito 5.4.6 from annotations
// in blood_pressure_monitor/test/views/profile/profile_picker_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i7;

import 'package:blood_pressure_monitor/models/profile.dart' as _i4;
import 'package:blood_pressure_monitor/services/profile_service.dart' as _i2;
import 'package:blood_pressure_monitor/viewmodels/active_profile_viewmodel.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileService extends _i1.Mock implements _i2.ProfileService {
  MockProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int> createProfile(_i4.Profile? profile) => (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<_i4.Profile?> getProfile(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [id],
        ),
        returnValue: _i3.Future<_i4.Profile?>.value(),
      ) as _i3.Future<_i4.Profile?>);

  @override
  _i3.Future<List<_i4.Profile>> getAllProfiles() => (super.noSuchMethod(
        Invocation.method(
          #getAllProfiles,
          [],
        ),
        returnValue: _i3.Future<List<_i4.Profile>>.value(<_i4.Profile>[]),
      ) as _i3.Future<List<_i4.Profile>>);

  @override
  _i3.Future<int> updateProfile(_i4.Profile? profile) => (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> deleteProfile(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [id],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<int> getProfileCount() => (super.noSuchMethod(
        Invocation.method(
          #getProfileCount,
          [],
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);
}

/// A class which mocks [ActiveProfileViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockActiveProfileViewModel extends _i1.Mock
    implements _i5.ActiveProfileViewModel {
  MockActiveProfileViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get activeProfileId => (super.noSuchMethod(
        Invocation.getter(#activeProfileId),
        returnValue: 0,
      ) as int);

  @override
  String get activeProfileName => (super.noSuchMethod(
        Invocation.getter(#activeProfileName),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.getter(#activeProfileName),
        ),
      ) as String);

  @override
  bool get isLoading => (super.noSuchMethod(
        Invocation.getter(#isLoading),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> loadInitial() => (super.noSuchMethod(
        Invocation.method(
          #loadInitial,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setActive(_i4.Profile? profile) => (super.noSuchMethod(
        Invocation.method(
          #setActive,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int> createProfile(
    _i4.Profile? profile, {
    bool? setAsActive = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
          {#setAsActive: setAsActive},
        ),
        returnValue: _i3.Future<int>.value(0),
      ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateProfile(_i4.Profile? profile) => (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProfile(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
